apiVersion: v2
appVersion: "1.0"
description: Divorce - Evidence Management Client Api
name: div-emca
version: 2.0.13
dependencies:
  - name: java
    version: 4.0.12
    repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"
